const LISTING_CATEGORIES = Object.freeze({
  EDUCATION: "EDUCATION",
  ELECTRONICS: "ELECTRONICS",
  FURNITURE: "FURNITURE",
  FASHION: "FASHION",
  SPORT: "SPORT",
});

module.exports = LISTING_CATEGORIES;