const LISTING_CATEGORIES = Object.freeze({
  EDUCATION: "EDUCATION",
  ELECTRONICS: "ELECTRONICS",
  FURNITURE: "FURNITURE",
  FASHION: "FASHION",
  SPORTS: "SPORTS",
});

module.exports = LISTING_CATEGORIES;