const LISTING_CATEGORIES = Object.freeze({
  BOOKS: "BOOKS",
  ELECTRONICS: "ELECTRONICS",
  FURNITURE: "FURNITURE",
  CLOTHING: "CLOTHING",
  OTHER: "OTHER",
});

module.exports = LISTING_CATEGORIES;